<a href="https://colab.research.google.com/github/elmago07/AI-ML-Learnings/blob/main/numpy_learnings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
print(np.__version__)

2.0.2


In [7]:
#Adding two lists using tarditional way and using Numpy

In [8]:
###Normal Python - Adding Two lists
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
restult = []
for i in range(len(list1)):
  restult.append(list1[i] + list2[i])
print("Python Result:", restult)

Python Result: [7, 9, 11, 13, 15]


In [9]:
#Numpy Adding two arrays
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result = array1 + array2
print("Numpy Result:", result)


Numpy Result: [ 7  9 11 13 15]


In [10]:
#Numpy Subracting two arrays
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result = array1 - array2
print("Numpy Result:", result)

Numpy Result: [-5 -5 -5 -5 -5]


In [11]:
#Numpy Multplying two arrays
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result = array1 * array2
print("Numpy Result:", result)

Numpy Result: [ 6 14 24 36 50]


In [13]:
#Numpy Division two arrays
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result = array2 / array1
print("Numpy Result:", result)

Numpy Result: [6.         3.5        2.66666667 2.25       2.        ]


In [15]:
#Numpy Operations
import numpy as np


In [16]:
a = np.array([1,2,3])

In [17]:
print(a)

[1 2 3]


In [19]:
print(a.size) #size of array

3


In [20]:
print(a.shape) #shape of array with rows and coloumns

(3,)


In [21]:
print(a.ndim) #dimension of an array

1


In [22]:
print(a.dtype) #data type of array

int64


In [25]:
print(a.nbytes) #total size of an array

24


In [28]:
#2D Array Exploration
import numpy as np
b = np.array([[1,2,3], [4,5,6]])
print(b)
print("Size of array:", b.size)
print("Shape of array:", b.shape)
print("Dimension of array:", b.ndim)
print("DataType of array:", b.dtype)


[[1 2 3]
 [4 5 6]]
Size of array: 6
Shape of array: (2, 3)
Dimension of array: 2
DataType of array: int64


In [37]:
#Indexing in 1D array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("First Element:", arr[0])
print("Second Element:", arr[1])
print("Third Element:", arr[2])
print("Fourth Element:", arr[3])
print("Fifth Element:", arr[5])
print("Last Element:", arr[9])
print("Last Element:", arr[-1]) # prints last element in the array.
print("Second Last Element:", arr[-2]) # prints Second last element in the array.
print("Third Last Element:", arr[-3]) # prints Third last element in the array.
print("Last Element:", arr[10]) # throws an error.

First Element: 1
Second Element: 2
Third Element: 3
Fourth Element: 4
Fifth Element: 6
Last Element: 10
Last Element: 10
Second Last Element: 9
Third Last Element: 8


IndexError: index 10 is out of bounds for axis 0 with size 10

In [44]:
#Indexing in 2D array
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[0,2]) #prints 3
print(arr[1,1]) #prints 5
print(arr[2,0]) #prints 7

3
5
7


In [47]:
#Slicing:getting a part of the array using a range of positions.
#Slicing in 1D array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:5]) #prints 1,2,3,4,5
print(arr[5:]) #prints 6,7,8,9,10
print(arr[:5]) #prints 1,2,3,4,5
print(arr[-5:-1]) #prints 6,7,8,9
print(arr[0:5:2]) #prints 1,3,5
print(arr[::2]) #prints 1,3,5,7,9
print(arr[1::2]) #prints 2,4,6,8,10
print(arr[::-1]) #prints 10,9,8,7,6,5,4,3,2,1




[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]
[6 7 8 9]
[1 3 5]
[1 3 5 7 9]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3  2  1]
